//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beserproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberler
    {
        public int HaberId { get; set; }
        public string HaberBaslik { get; set; }
        public string HaberIcerik { get; set; }
        public System.DateTime HaberTarih { get; set; }
        public string HaberFoto { get; set; }
        public int HaberUyeId { get; set; }
        public int HaberKatId { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
